
import java.awt.Image;
import java.awt.Toolkit;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SGW08
 */
public class OPC1 extends javax.swing.JFrame {

    /**
     * Creates new form OPC1
     */
    public OPC1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconUAM() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/IconUAM.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        CD = new javax.swing.JButton();
        DVD = new javax.swing.JButton();
        LIBRO = new javax.swing.JButton();
        REVISTA = new javax.swing.JButton();
        jButton5Regresar = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconUAM());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TITULO.setText("Agregar Producto ");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        CD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CD.setText("1.CD");
        CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDActionPerformed(evt);
            }
        });
        getContentPane().add(CD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        DVD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DVD.setText("2.DVD");
        DVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DVDActionPerformed(evt);
            }
        });
        getContentPane().add(DVD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        LIBRO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LIBRO.setText("3.Libro");
        LIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIBROActionPerformed(evt);
            }
        });
        getContentPane().add(LIBRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        REVISTA.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        REVISTA.setText("4.Revista");
        REVISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REVISTAActionPerformed(evt);
            }
        });
        getContentPane().add(REVISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jButton5Regresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton5Regresar.setText("Regresar");
        jButton5Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo4.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REVISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REVISTAActionPerformed
        // TODO add your handling code here:
        Opc1Revistas revista=new Opc1Revistas();
        revista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_REVISTAActionPerformed

    private void jButton5RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5RegresarActionPerformed
        // TODO add your handling code here:
        MAIN menu = new MAIN();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5RegresarActionPerformed

    private void CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDActionPerformed
        // TODO add your handling code here:
        Opc1CD cd=new Opc1CD();
        cd.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_CDActionPerformed

    private void DVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DVDActionPerformed
        // TODO add your handling code here:
        Opc1Dvd dvd=new Opc1Dvd();
        dvd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DVDActionPerformed

    private void LIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIBROActionPerformed
        // TODO add your handling code here:
        Opc1Libros libros=new Opc1Libros();
        libros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LIBROActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPC1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CD;
    private javax.swing.JButton DVD;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton LIBRO;
    private javax.swing.JButton REVISTA;
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton jButton5Regresar;
    // End of variables declaration//GEN-END:variables
}
